---
id: use-error-boundary
title: useErrorBoundary
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import VersionedCodeBlock from '@theme/VersionedCodeBlock';

The `useErrorBoundary` hook allows KComponents to catch and handle errors higher up in the tree and provide appropriate fallback, logging or retry mechanisms. It corresponds to the Java Spec API's `@OnError` functionality. If you haven't already, make sure to review the [Hooks Intro](hooks-intro.mdx) docs to understand more about hooks.

## Conceptual Overview

A KComponent becomes an error boundary when it declares a `useErrorBoundary` hook.
The hook parameter will receive all exceptions that are raised in the lifecycle methods of components sitting underneath the error boundary in the tree, regardless of whether those are other KComponents or Litho Specs.

The KComponent can leverage the [`useState` hook](use-state.mdx), to update the state with the exception that was caught, then trigger a render pass with the new state value in order to replace the crashing component with an error component, or not display it at all.

<Tabs
  groupId="error_boundary"
  defaultValue="kotlin_state"
  values={[
    {label: 'Kotlin', value: 'kotlin_state'},
    {label: 'Java', value: 'java_state'},
  ]}>
  <TabItem value="kotlin_state">

```kotlin file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KErrorBoundary.kt start=start_example end=end_example
```

  </TabItem>
  <TabItem value="java_state">

```java file=sample/src/main/java/com/facebook/samples/litho/java/errors/ErrorBoundarySpec.java start=start_example end=end_example
```
  </TabItem>

</Tabs>

An error boundary may choose to only handle certain classes of errors. You can re-raise an exception from within the `useErrorBoundary` hook so that it propagates up the component tree until it is either caught by another error boundary or hits the root and causes a crash. This is done by calling [`ComponentUtils.raise`](pathname:///javadoc/com/facebook/litho/ComponentUtils.html#raise-com.facebook.litho.ComponentContext-java.lang.Exception-) with your context and the exception.

## Why not Try/Catch?

You may wonder why all this additional infrastructure would be necessary when you could just use try/catch. It turns out that there is no easily accessible place to wrap your Component code like this.

The following example shows how not to do it:

<Tabs
  groupId="error_boundary_try_catch"
  defaultValue="kotlin_state"
  values={[
    {label: 'Kotlin', value: 'kotlin_state'},
    {label: 'Java', value: 'java_state'},
  ]}>
  <TabItem value="kotlin_state">

```kotlin file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KIncorrectErrorHandlingComponent.kt start=start_example end=end_example
```

  </TabItem>
  <TabItem value="java_state">

```java file=sample/src/main/java/com/facebook/samples/litho/java/errors/IncorrectErrorHandlingComponentSpec.java start=start_example end=end_example
```
  </TabItem>

</Tabs>

Assuming that PossiblyCrashingSubTitleComponent throws an exception in onCreateLayout this would not be caught by this block. The reason for this is that you are just returning a declaration of your layout here and don't actually execute any code. This is the responsibility of the Litho framework, hence the need to provide higher-level infrastructure to give you access to those errors.
